# Generated by Django 4.2.5 on 2023-10-01 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('todos', models.JSONField()),
            ],
        ),
    ]
