# Generated by Django 4.2.5 on 2023-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default='tom@gmail.com', max_length=254),
        ),
    ]
